name: flutter_mediasoup_client
version: 0.0.1
author: cloudwebrtc <duanweiwei1982@gmail.com>
description: Flutter version of the mediasoup-client library. 
homepage: https://github.com/cloudwebrtc/flutter-mediasoup-client
environment:
  sdk: '>1.8.0 <3.0.0'

dependencies:
  events2: ^0.1.3
  flutter_webrtc: ^0.1.5
  protoo_client: ^0.1.0
  sdp_transform: ^0.1.0
